# Generated by Django 3.2.4 on 2021-07-04 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SITIO', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorias',
            new_name='Categoria',
        ),
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
    ]
