# Generated by Django 3.2.4 on 2021-07-04 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SITIO', '0002_auto_20210704_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripcion',
            new_name='descripcion_producto',
        ),
    ]
