# Generated by Django 3.2.4 on 2021-07-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITIO', '0004_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='lista_productos',
            field=models.ManyToManyField(blank=True, related_name='carrito', to='SITIO.Producto'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='total_carrito',
            field=models.FloatField(blank=True),
        ),
    ]
